language: python
python:
  - "3.8"
# command to install dependencies
install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
# command to run tests
script:
  - pytest
